---
deployment:
  tasks:
    - export DEPLOYPATH=/home/yusklr/melvicgomez.com/testing-folder
    - gatsby build
    - /bin/rm -Rf $DEPLOYPATH
    - /bin/mkdir $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH