---
deployment:
  tasks:
    - export DEPLOYPATH=/home/yuxsulkr/melvicgomez.com/testing-folder
    - /bin/rm -rf $DEPLOYPATH
    - /bin/mkdir $DEPLOYPATH
    # - /bin/cp .cpanel.yml $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
