---
deployment:
  tasks:
    - export DEPLOYPATH=/home/yuxsulkr/melvicgomez.com/testing-folder
    - /home/yuxsklr/bin/gatsby build
    - /bin/rm -Rf $DEPLOYPATH
    - /bin/mkdir $DEPLOYPATH
    # - /bin/cp .cpanel.yml $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
