---
deployment:
  tasks:
    - export DEPLOYPATH=/home/yuxsklr/melvicgomez.com/testing-folder
    # - /bin/gatsby build
    - /bin/rm -Rf $DEPLOYPATH
    - /bin/mkdir $DEPLOYPATH
    - /bin/cp .cpanel.yml $DEPLOYPATH
    # - /bin/cp -R public $DEPLOYPATH