name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build: # set depends on what you need
    name: Build and Artifact
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Create .env file
        env:
          CMS_URL: ${{ secrets.CMS_URL }}
        run: echo "$CMS_URL" >> .env

      - name: Install dependencies and build project
        run: |
          npm ci
          npm run build

      - name: Create zip file of public directory
        run: tar -zcvf bundle.tar.gz -C public/ .

      - name: Store bundle in artifact
        uses: actions/upload-artifact@v2
        with:
          name: bundle-tar
          path: bundle.tar.gz

  deploy: # set depends on what you need
    name: Deploy project
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: bundle-tar

      - name: Check bundle tar info
        run: ls
