name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build: # set depends on what you need
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Create .env file
        env:
          CMS_URL: ${{ secrets.CMS_URL }}
        run: echo "$CMS_URL" >> .env

      - name: Install dependencies and build project
        run: |
          npm ci
          npm run build

      - name: Create zip file of public directory
        run: tar -zcvf bundle.tar.gz -C public/ .

      - name: Store bundle in artifact
        uses: actions/upload-artifact@v2
        with:
          name: bundle-tar
          path: bundle.tar.gz
          retention-days: 1

  deploy: # set depends on what you need
    name: Deploy project
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download bundle artifact from previous job
        uses: actions/download-artifact@v2
        with:
          name: bundle-tar

      - name: Upload bundle tar file in Hostinger using FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          server-dir: ${{ secrets.FTP_ARCHIVE_DEST }}

      - name: Extract and copy files in public_html directory using ssh
        uses: appleboy/ssh-action@master
        env:
          RELEASE_DIR: ${{ secrets.RELEASE_DIR }}
          ARCHIVE_DIR: ${{ secrets.ARCHIVE_DIR }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          envs: RELEASE_DIR,ARCHIVE_DIR
          script: |
            # rm -rf "$RELEASE_DIR/*"
            cd "$ARCHIVE_DIR/"
            tar -C "$RELEASE_DIR/" -xzvf bundle.tar.gz
            # rm -rf bundle.tar.gz
